### ISSUE TITLE
q18) let variables do not get Hoisted.

### ISSUE THREAD

**Issue by hitesh19** [sudheerj/javascript-interview-questions#10]
Hi,

Could you please review this point that 'let variables do not get hoisted' in q18, as i read that let variables also get hoisted but lead to a temporal dead zone(TDZ).

PFB the link to the article - 
http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified

**Comment by sudheerj** [comment]
The statement has been corrected. Thanks.
