### ISSUE TITLE
Incorrect answer for #227 question

### ISSUE THREAD

**Issue by gitaramp** [sudheerj/javascript-interview-questions#101]
The Question is about SyntaxError, but the answer is about EvalError

**Comment by sudheerj** [comment]
The output is not consistent. Need to find the exact reason for this

![image](https://user-images.githubusercontent.com/3127317/147274135-798c45aa-64bd-46be-8b63-89cadaa7e8ae.png)

**Comment by gitaramp** [comment]
I got an EvalError, because i tried execute this code in the chrome console where Content Security Police blocks eval funcitons.

**Comment by sudheerj** [comment]
Thanks for the clarification
