### ISSUE TITLE
Incorrect variable name - Q 412 

### ISSUE THREAD

**Issue by JITES** [sudheerj/javascript-interview-questions#102]
function isPromise(object){
      if(Promise && Promise.resolve){
      return Promise.resolve(object) == object;
      }else{
      throw "Promise not supported in your environment"
      }
   }

   var i = 1;
   var promise = new Promise(function(resolve,reject){
      resolve()
   });

   console.log(isPromise(i)); // false
   console.log(isPromise(p)); // true *correction* // promise

**Comment by sudheerj** [comment]
@JITES Thanks for notifying. Fixed.

**Comment by JITES** [comment]
Hey Sudheerj,

thanks to you as well. This is really helpful.


~
Jitesh
