### ISSUE TITLE
Mistake in Coding Exercise #57

### ISSUE THREAD

**Issue by ddubrava** [sudheerj/javascript-interview-questions#108]
`console.log(true && '' && 0);` returns `''`. The operator returns the value of the first falsy operand encountered when evaluating from left to right, or the value of the last operand if they are all truthy.

![image](https://user-images.githubusercontent.com/22116465/149846521-debdd9d3-3d35-4337-9088-d4247400eaa1.png)
![image](https://user-images.githubusercontent.com/22116465/149846552-41382409-1928-49ef-bc31-5717d88e6964.png)

**Comment by sudheerj** [comment]
Thanks @ddubrava . Fixed
