### ISSUE TITLE
1.3 question

### ISSUE THREAD

**Issue by gwyndoln** [sudheerj/javascript-interview-questions#115]
>The object literal syntax is equivalent to create method when it passes null as parameter
No, now literal syntax is create object with Object [[prototype]]

**Comment by sudheerj** [comment]
@gwyndoln I didn't get the exact details of this issue. Can you provide more details?

**Comment by gwyndoln** [comment]
@sudheerj Object.create(null) creates an object with no properties and no [[prototype]] property, literal syntax: "let obj = {}" creates an object with "[[prototype]]: Object.prototype" property

**Comment by sudheerj** [comment]
Thanks @gwyndoln  👍 I corrected it
