### ISSUE TITLE
The answer may be wrong?

### ISSUE THREAD

**Issue by viprespro** [sudheerj/javascript-interview-questions#124]
The answer of  questions about rest parameters may be wrong in **No.23 and No.35** which might be misleading.

![example](https://user-images.githubusercontent.com/38908500/164193302-c99bae8e-6216-4535-9f17-c9e13692e3df.png)

**Comment by gouravghosh24** [comment]
1

**Comment by Hemantch1998** [comment]
1 option [2,3,4,5]

**Comment by sudheerj** [comment]
The question 23 has been updated and 35 will be replaced with new one. Thanks for pointing out

**Comment by mtalhasahin** [comment]
1,[2,3,4,5]
