### ISSUE TITLE
Coding exercise 5 answer incorrect?

### ISSUE THREAD

**Issue by camden-kid** [sudheerj/javascript-interview-questions#127]
I ran the code for exercise 5 in the Chrome developer console and the output was "1function". The stated answer suggests "1undefined", unless I am reading it incorrectly.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/890197/169644538-87c2099e-b468-4de9-a8b3-163f88ea198b.png">

**Comment by MuhammedZakir** [comment]
Like other stuff, it depends on the browser. Both Firefox and WebKit ouput `1undefined`.

**Comment by camden-kid** [comment]
Interesting. Maybe add that to the Note of the answer?

**Comment by sudheerj** [comment]
I'm receiving 1undefined in chrome browser and the version is 101.0.4951.64

**Comment by camden-kid** [comment]
Hi @sudheerj I just upgraded Chrome on the Mac to Version 102.0.5005.61 and now `1undefined` is output. I forgot to check which version I used previously but I think you can close this issue. I tested the code on Firefox and Safari and both output `1undefined`.

However, the first point to the answer states:
"You can see function expression instead function declaration inside if statement. So it always returns true."

Maybe change that to:
"You can see a function declaration inside the if statement. So it always returns true."
 
On a side note, I find this confusing. Maybe someone could explain it:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/890197/170861056-7d18486e-fbcc-47a8-838c-c0bb2736faab.png">
