### ISSUE TITLE
Coding Exercise Question Number 35

### ISSUE THREAD

**Issue by waqarorakzai** [sudheerj/javascript-interview-questions#130]
https://github.com/sudheerj/javascript-interview-questions#35-what-is-the-output-of-below-code

`const [x, ...y] = [1, 2, 3, 4];
console.log(x, y);`

There is not syntax error: 
The answer will be the first one. It is getting first item in array in the x  and rest will be in y
So the answer is 1

**Comment by Kaushik-Iyer** [comment]
Can i work on this?

**Comment by ntsagar9** [comment]
**Question:** 
const [x, ...y, z] = [1, 2, 3, 4];
console.log(x, y, z);

**Options**
1: 1, [2, 3], 4
2: 1, [2, 3, 4], undefined
3: 1, [2], 3
4: SyntaxError

**Answer is option 4 SyntaxError**

Your question is also current x is first element then rest of is on y.

Thank you,
Sagar Tank

**Comment by sudheerj** [comment]
@ntsagar9 @waqarorakzai  The question and answer has been updated.
