### ISSUE TITLE
Why JS is  interpretation language?

### ISSUE THREAD

**Issue by mikeblatson** [sudheerj/javascript-interview-questions#131]
I read the book You don't know JS. and Kyle Simpson believes in JS compiler language, not interpreation.  Can everyone proof Kyle Simpson?

**Comment by asqararslonov** [comment]
Hi Mike,
I can't give you a definitive answer. But JS is a streaming programming language. JS works together in both. 
You know it works based on Chrome V8. V8 is interpreted as both a compiler.
It's called JIT (Just in Time). I recommend learning this truth.

**Comment by sudheerj** [comment]
JavaScript is still an interpreted language but it has critical phase of compiler known as syntax analysis unlike other interpreted language. Also V8 has JIT to improve the performance of code execution.
