### ISSUE TITLE
Object.freez() missing part/concept

### ISSUE THREAD

**Issue by AhmadrezaMozaffary** [sudheerj/javascript-interview-questions#139]
When we are using `freez()` method in `Object` object, we do freez only top level key-value pairs not the nested object 

`
const obj = Object.freeze({
a: 10,
obj2: {c: 3}
});
console.log(obj)    // returns: {a: 10, obj2:{c: 3}}

obj.a = 11;
console.log(obj)    // returns: {a: 10, obj2:{c: 3}}

obj.obj2.c = 5;
console.log(obj)    // returns: {a: 10, **obj2:{c: 7}**}

`

**Comment by sudheerj** [comment]
@AhmadrezaMozaffary Thanks for sharing more details on freeze. It has been updated.
