### ISSUE TITLE
Fixed question 246 len not defined, replaced with length

### ISSUE THREAD

**Issue by elthask** [sudheerj/javascript-interview-questions#154]
var marks = [50, 20, 70, 60, 45, 30];
function findMin(arr) {
  var length = arr.length;
  var min = Infinity;
  while (length--) {
    if (arr[length] < min) {
      min = arr[length];
    }
  }
  return min;
}

function findMax(arr) {
  var length = arr.length;
  var max = -Infinity;
  while (length--) {
    if (arr[length] > max) {
      max = arr[length];
    }
  }
  return max;
}

console.log(findMin(marks));
console.log(findMax(marks));

**Comment by sudheerj** [comment]
Thanks @elthask. It has been fixed
