### ISSUE TITLE
Corrected question 245

### ISSUE THREAD

**Issue by elthask** [sudheerj/javascript-interview-questions#155]
const marks = [50, 20, 70, 60, 45, 30];
function findMin(arr) {
  return Math.min.apply(null, [...arr]);
}
function findMax(arr) {
  return Math.max.apply(null, [...arr]);

}
console.log(findMin(marks));
console.log(findMax(marks));

**Comment by sudheerj** [comment]
You don't need to use spread operator for Math.min.apply and Math.max.apply

**Comment by elthask** [comment]
Maybe, but the code doesn't run as is.
