### ISSUE TITLE
216:What are javascript accessors? missing comma before set lang

### ISSUE THREAD

**Issue by nikikalwar** [sudheerj/javascript-interview-questions#161]
var user = {
  firstName: "John",
  lastName : "Abraham",
  language : "en",
  get lang() {
    return this.language;
  },
  set lang(lang) {
  this.language = lang;
  }
};
console.log(user.lang); // getter access lang as en
user.lang = 'fr';
console.log(user.lang);

before the set method, there needs to be a comma else it will throw an error

**Comment by sudheerj** [comment]
Closing this issue considering merged PR
