### ISSUE TITLE
Answer provided is wrong

### ISSUE THREAD

**Issue by Prathapkarumanchi** [sudheerj/javascript-interview-questions#180]
Hi,
For this coding example - the answer is given as 1 where as the `new Set()` will create unique values but it should be array not an object.

https://github.com/sudheerj/javascript-interview-questions#20-what-is-the-output-of-below-code

```
const numbers = new Set([1, 1, 2, 3, 4]);
console.log(numbers);

const browser = new Set("Firefox");
console.log(browser);

-------------------------------------------

Set(4) [ 1, 2, 3, 4 ]
Set(7) [ "F", "i", "r", "e", "f", "o", "x" ]
```

**Comment by sudheerj** [comment]
@Prathapkarumanchi It creates an object but not array. 
![image](https://user-images.githubusercontent.com/3127317/229547207-9730ec84-5524-4f8b-9ded-22ed632281e6.png)
