### ISSUE TITLE
1. What are the possible ways to create objects in JavaScript

### ISSUE THREAD

**Issue by nikikalwar** [sudheerj/javascript-interview-questions#188]
There are many ways to create objects in javascript as below

    Object constructor:

    The simplest way to create an empty object is using the Object constructor. Currently this approach is not recommended.

    var object = new Object();

Regarding this, the Object() is a built-in constructor function so "new" keyword is not required. the above can be written as:
 var object = Object();

**Comment by Manibhardawaj** [comment]
In JavaScript, there are multiple ways to create objects.
 
Here are some of the most common methods:

Object Literal: 

The simplest way to create an object is by using an object literal, which is a comma-separated list of key-value pairs enclosed in curly braces:

const person = { name: 'John', age: 30, occupation: 'Engineer', }; 

Constructor Function:

You can create objects using constructor functions. A constructor function is a regular function that is used with the new keyword to create instances of objects.


function Person(name, age, occupation) { this.name = name; this.age = age; this.occupation = occupation; } const person = new Person('John', 30, 'Engineer'); 

Object.create(): 

The Object.create() method creates a new object, using an existing object as the prototype of the newly created object.


const personPrototype = { introduce() { console.log(`Hello, my name is ${this.name}.`); } }; const person = Object.create(personPrototype); person.name = 'John'; person.age = 30; person.occupation = 'Engineer'; 

Class (ES6+): 

ES6 introduced classes, which provide a more intuitive way to create objects with constructor functions and methods.


class Person { constructor(name, age, occupation) { this.name = name; this.age = age; this.occupation = occupation; } introduce() { console.log(`Hello, my name is ${this.name}.`); } } const person = new Person('John', 30, 'Engineer'); 

Factory Functions:

 Factory functions are functions that return objects. They can be used to encapsulate the object creation process.

function createPerson(name, age, occupation) { return { name: name, age: age, occupation: occupation, }; } const person = createPerson('John', 30, 'Engineer'); 

ES6 Destructuring:

With ES6 destructuring, you can create objects directly from variables:


const name = 'John'; const age = 30; const occupation = 'Engineer'; const person = { name, age, occupation }; 

Each of these methods has its own use case and advantages, so choose the one that best fits your specific scenario and coding style.

**Comment by sudheerj** [comment]
Thanks. It has been updated.
