### ISSUE TITLE
Not able to download the PDF

### ISSUE THREAD

**Issue by pranavmappoli** [sudheerj/javascript-interview-questions#192]

**Comment by PamzyS** [comment]
Any update on this issue. Not able to see a download link for PDF.

**Comment by manojmula** [comment]
[js2.pdf](https://github.com/sudheerj/javascript-interview-questions/files/11870617/js2.pdf)
I have converted to pdf , please refer to this , if any details are needed , please comment below.

**Comment by sudheerj** [comment]
PDF version has been misused by some members. Hence there is no more support with pdf
