### ISSUE TITLE
Question 311

### ISSUE THREAD

**Issue by rayoowoo** [sudheerj/javascript-interview-questions#20]
For question 311 on tagged templates, the function myInfoTag is missing a parameter.

Currently:
`function myInfoTag(strings, userExp, experienceExp) {`

It should be:
`function myInfoTag(strings, userExp, experienceExp, skillExp) {`

`skillExp` is referenced in the function body, but is not an parameter. 

Also, 
The two `console.log`'s should have `output1` and `output2` as arguments.

`console.log(output1);// Mr/Ms. John is a/an expert developer in JavaScript`
`console.log(output2);// Mr/Ms. Kane is a/an junior developer in JavaScript`

**Comment by sudheerj** [comment]
Thanks for the details. Fixed
