### ISSUE TITLE
Q.185: What is a rest parameter - Example with error

### ISSUE THREAD

**Issue by bipiane** [sudheerj/javascript-interview-questions#206]
Hi, 
there is an error calling the function and the code has the wrong format.

[Q.185: What is a rest parameter](https://github.com/sudheerj/javascript-interview-questions#what-is-a-rest-parameter: )
```javascript
function total(…args){
let sum = 0;
for(let i of args){
sum+=i;
}
return sum;
}
console.log(fun(1,2)); //3
console.log(fun(1,2,3)); //6
console.log(fun(1,2,3,4)); //13
console.log(fun(1,2,3,4,5)); //15
``` 
Can I make a PR?

P.S. Thanks for collecting all the questions!

**Comment by sudheerj** [comment]
Thanks @bipiane for the finding. Fixed it.
