### ISSUE TITLE
Organization of the questions.

### ISSUE THREAD

**Issue by jassi369** [sudheerj/javascript-interview-questions#209]
### Questions should be organized 
1. **It will make it easier for users to find the questions they are looking for**. Currently, the questions are not organized in any way, so it can be difficult to find the ones you need. Categorizing the questions will make it much easier for users to find the ones that are relevant to their interests.
2. **It will help users to learn more effectively. Categorized information is easier to retain in memory**. When questions are categorized, users can see the relationships between different topics. This can help them to learn more effectively by understanding how the different topics are connected.
### **How to organize questions?**
1.**By topic**: This is the most common way to categorize questions. Questions can be categorized by topic, such as object-oriented programming, functional programming, event handling, and so on.
2. **By difficulty level:** Questions can be categorized by difficulty level, such as beginner, intermediate, and advanced. This can help users to find questions that are appropriate for their skill level.

**Comment by sudheerj** [comment]
@jassi369  Thanks for your feedback. There is a plan to organize them in a better way similar to by topic or by difficulty level. I will update in this thread once it is finished.
