### ISSUE TITLE
Q207. What is the purpose of uneval - deprecated

### ISSUE THREAD

**Issue by d9k** [sudheerj/javascript-interview-questions#213]
Uneval is deprecated and **removed** from modern browsers:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features#acquiring_source_text

One should use `fn.toString()` for functions and `JSON.stringify()` for data.

```
> function sum(a, b) { return a + b; }
> sum.toString()
'function sum(a, b) { return a + b; }'
```

**Comment by sudheerj** [comment]
Thanks @d9k for pointing out. The answer has been updated.
