### ISSUE TITLE
Q378 How do you capture browser back button

### ISSUE THREAD

**Issue by d9k** [sudheerj/javascript-interview-questions#215]
This code doesn't seem to work anymore due to modern browsers security restriction:

```js
window.onbeforeunload = function () {
  alert("You work will be lost");
};
```

https://stackoverflow.com/a/58064395/1760643 (2019):

> Onbeforeunload is subject of one of bigest missunderstanding in the webdevelopers world :D
>
> 1) It **refuses to call** all blocking native functions (**alert**, prompt, confirm). It is obvious from User perspective.

This code works:

```js
window.onbeforeunload = function () {
  console.log("onbeforeunload");
};
```

**Comment by sudheerj** [comment]
@d9k The answer for this question has been updated. Thank you for creating the issue.
