### ISSUE TITLE
E23 (array destructuring): no expected error

### ISSUE THREAD

**Issue by d9k** [sudheerj/javascript-interview-questions#216]
Coding excercise 23

https://github.com/sudheerj/javascript-interview-questions#23-what-is-the-output-of-below-code

> When using rest parameters, trailing commas are not allowed 

But there is no trailing comma in task description:

```
let [a, ...b] = [1, 2, 3, 4, 5];
console.log(a, b);
```

This code doesn't cause `SyntaxError` as described.

**Comment by d9k** [comment]
Also E24 is missing.

![Screenshot from 2023-09-20 18-28-18](https://github.com/sudheerj/javascript-interview-questions/assets/7331988/f15798f9-2a18-4607-9abb-2125fdca45c3)

**Comment by sudheerj** [comment]
Thank you @d9k . The typo has been fixed. We skipped this question intentionally to add a specific question.
