### ISSUE TITLE
Answer 8

### ISSUE THREAD

**Issue by ChinmayaBisoi** [sudheerj/javascript-interview-questions#222]
Answer 8, point V,

An Object has a prototype, so there are default keys in the **map** that could collide with your keys if you're not careful. As of ES5 this can be bypassed by using map = Object.create(null), but this is seldom done.

I believe you meant **object** instead of **map** there?

**Comment by mrAJAY1** [comment]
Yes. The answer seems to be a bit confusing.

**Comment by sudheerj** [comment]
It has been fixed. Thank you
