### ISSUE TITLE
Spelling error in README.md

### ISSUE THREAD

**Issue by kenshanta** [sudheerj/javascript-interview-questions#253]
Should instead be "Any primitive type"?

<img width="897" alt="Screenshot 2024-05-14 at 1 04 12 AM" src="https://github.com/sudheerj/javascript-interview-questions/assets/83559262/1ebbe8c8-8a58-45cc-ba0d-20eefb393901">

**Comment by sudheerj** [comment]
@kenshanta  Mentioned it explicitly. Thanks
