### ISSUE TITLE
Inadequate information & grammar fix suggestion

### ISSUE THREAD

**Issue by kenshanta** [sudheerj/javascript-interview-questions#254]
Not a major issue as the context can be understood without focusing on the semantics.

- In the Second Topic: - Maybe its my bad habit of overthinking, but regardless wanted to ask the author for clearance on the matter - so far there are 2 possible intents from the following sentence:
 ```prototype on constructors function is available through Object.prototype.```
 1. prototype on ```constructor's``` function is available through Object.prototype.
 2. prototype on constructor ```functions``` is available through Object.prototype.

By default the first option is invalid as its commonly advised against to define methods nested in the constructor function (unless its via the prototype obj)
So I assume the second option is the correct form. *(waiting to hear back on this)*
 
 Ideally I suggest starting the section with additional information before getting to the point on how to utilize the prototype object; for example:
```
When you create an object using a constructor function or a class, the created object inherits properties from a prototype object.
// CURRENT SENTENCE The prototype on object instance is available....
```
 
<img width="920" alt="Screenshot 2024-05-16 at 6 30 42 PM" src="https://github.com/sudheerj/javascript-interview-questions/assets/83559262/7a1021fe-5312-4223-a0b3-7d1550525190">

**Comment by sudheerj** [comment]
@kenshanta  Thanks for the details. It has been corrected.
