### ISSUE TITLE
#347 Error

### ISSUE THREAD

**Issue by DmitriyMalayev** [sudheerj/javascript-interview-questions#257]
Hi, Thanks for the amazing guide. 
There is a syntax error on question # 347 

let regexp = /Hello(\d?))/g;     //extra ) 
let greeting = "Hello1Hello2Hello3";

let greetingList = [...greeting.matchAll(regexp)];

console.log(greetingList[0]); //Hello1
console.log(greetingList[1]); //Hello2
console.log(greetingList[2]); //Hello3

**Comment by sudheerj** [comment]
@DmitriyMalayev  Thanks for pointing out. Fixed.
