### ISSUE TITLE
Question No 1

### ISSUE THREAD

**Issue by abhiupadhyay-Dev** [sudheerj/javascript-interview-questions#284]
let vehicle = {
  wheels: '4',
  fuelType: 'Gasoline',
  color: 'Green'
}

let carProps = {
  type: {
    value: 'Volkswagen',
    enumerable:true
  },
  model: {
    value: 'Golf',
    enumerable:true
  }
}

var car = Object.create(vehicle, carProps);
console.log(car);

Make this property enumerable means visible else it will be empty {}

**Comment by sudheerj** [comment]
@abhiupadhyay-Dev We don't have any question as you mentioned

**Comment by abhiupadhyay-Dev** [comment]
the first one create object
