### ISSUE TITLE
Proposal: Add a disclaimer for aspiring developers

### ISSUE THREAD

**Issue by OriginalEXE** [sudheerj/javascript-interview-questions#29]
Hello,

First of all, thanks for maintaining this list, I am sure it takes a lot of effort, and it has already helped many people.

I would like to suggest (and I am open for discussion) to add a disclaimer somewhere at the top that clarifies the purpose of the repository in more detail. As it is now, it can be pretty scary for aspiring developers, as it might make them think one has to know the answer to all these questions in order to pass an interview for what might probably be their first job in web development (I am speaking from my personal experience - a person I am mentoring is how I found out about this repo).

I would be happy to help and come up with/give feedback on such a text.

Let me know what you think, and thanks again for your efforts, appreciated!
Ante

**Comment by sudheerj** [comment]
@OriginalEXE  I agree with your feedback. We don't need to know answers for all those questions to pass an interview. But it gives all possible questions to crack an interview with deep knowledge on javascript.  It would be great if you can provide the feedback on text.

**Comment by sagar-gavhane** [comment]
I'm happy to contribute to this 😀. Can I raise PR for including a disclaimer?

**Comment by sudheerj** [comment]
@sagar-gavhane It would be great. Thanks

**Comment by sagar-gavhane** [comment]
**Disclaimer**

The question and answers provided in this repository are based on frequently asked questions. We cannot guarantee that the same questions will be get asked during the interview process. Don't worry just be prepared for it 😊.


@sudheerj

**Comment by OriginalEXE** [comment]
Thank you for coming up with a proposal Sagar!

My suggestion building on top of yours:

---

The questions provided in this repository are the summary of frequently asked questions across numerous companies. We cannot guarantee that these questions will actually be asked during _your_ interview process, nor should you focus on memorizing all of them. The primary purpose is for you to get a sense of what some companies might ask — do not get discouraged if you don't know the answer to all of them ⁠— that is ok!

Good luck with your interview 😊

---

Let me know what you think about this? I tried to add additional encouragement and point out that one doesn't need to know the answer to all of these to get a job.

**Comment by sudheerj** [comment]
@sagar-gavhane  @OriginalEXE  Thank you for the content of disclaimer. It is helpful for the readers with a positive mindset :)
