### ISSUE TITLE
Super Array Of Objects

### ISSUE THREAD

**Issue by inblack67** [sudheerj/javascript-interview-questions#30]
### Count the occurrence of keys and convert the result into array of objects where each object belongs to one key and it's occurrence (count).
eg. 

```js
[{ language: 'JavaScript' },{ language: 'JavaScript' },{ language: 'TypeScript' },] 
```

### SHOULD BE CONVERTED TO:-

```js
[
{ language: 'JavaScript', count: 2 },
{ language: 'C++', count: 1 },
{ language: 'TypeScript', count: 1 }
]
```

## Sounds good?

**Comment by sudheerj** [comment]
@inblack67  Can you elaborate about this question?

**Comment by inblack67** [comment]
The idea is to count the frequency of each unique key in an array of objects and then instead of making the result look like 
```js
{ key1: 2, key2: 1, key3: 7 } 
```
The result should be an array of objects so that it can be map over and get rendered in React.JS or something like that.
```js
[ { key1: 2 }, { key2: 1 }, { key3: 7 } ]
```

**Comment by inblack67** [comment]
@sudheerj  Pull Request Awaits To Be Merged.
