### ISSUE TITLE
Mistake in Coding Exercise #18

### ISSUE THREAD

**Issue by arturjzapater** [sudheerj/javascript-interview-questions#37]
The exercise and the provided answer don't match. Specifically, there is a problem with the first line:
```javascript
console.log([0] === false);
```

The answer claims that `[0]` is coerced to `Number([0].valueOf().toString())`, which is then coerced to `false`. However, this is untrue because the identity operator (`===`) doesn't perform type coercion. So the following expressions all return `false`
```javascript
[0] === Number([0].valueOf().toString())
[0] === 0
[0] === false
```

I see two different ways to fix the exercise:
- Change the accepted answer to "3: False, I'm True"
- Change line 1 of the problem to use the equality operator (`==`) instead.

**Comment by sudheerj** [comment]
@arturjzapater  Thank you for pointing out. Fixed it with == operator.
