### ISSUE TITLE
Should divide questions in sets (Easy / intermediate / expert) !!!

### ISSUE THREAD

**Issue by omkarvp99** [sudheerj/javascript-interview-questions#39]
As we can see questions are listed but not sorted for users who are referring to these questions.
IT should be sort according to the level of respective question like an easy or expert level question, like that.
So request to add sections/divisions to separate questions with the difficulty level of respective questions.

**Comment by sudheerj** [comment]
@omkarvp99  Thank for your feedback. I will do these changes in coming days
