### ISSUE TITLE
What is the purpose of array splice method?

### ISSUE THREAD

**Issue by devpato** [sudheerj/javascript-interview-questions#4]
Questions 6.
**What is the purpose of array splice method?**

**Actual code**
```
let arrayIntegersOriginal1 = [1, 2, 3, 4, 5];
let arrayIntegersOriginal2 = [1, 2, 3, 4, 5];
let arrayIntegersOriginal3 = [1, 2, 3, 4, 5];

let arrayIntegers1 = arrayIntegersOriginal1.splice(0,2); // returns [1, 2]; original array: [3, 4, 5]
let arrayIntegers2 = arrayIntegersOriginal2.splice(3); // returns [4, 5]; original array: [1, 2, 3]
let arrayIntegers3 = arrayIntegersOriginal3.splice(3, 1, "a", "b", "c"); //returns [4]; original array: [1, 2, 3, "a", "b", "c", 5]
```

**Should be:**
```
let arrayIntegersOriginal1 = [1, 2, 3, 4, 5];
let arrayIntegersOriginal2 = [1, 2, 3, 4, 5];
let arrayIntegersOriginal3 =  [1, 2, 3, "a", "b", "c", 5];

let arrayIntegers1 = arrayIntegersOriginal1.splice(0,2); // returns [1, 2]; original array: [3, 4, 5]
let arrayIntegers2 = arrayIntegersOriginal2.splice(3); // returns [4, 5]; original array: [1, 2, 3]
let arrayIntegers3 = arrayIntegersOriginal3.splice(3, 1, "a", "b", "c"); //returns ["a"]; original array: [1, 2, 3, "a", "b", "c", 5]
```

This code actually returns ["a"] and the original array needs to be updated

**Comment by sudheerj** [comment]
It returns the correct array

![image](https://user-images.githubusercontent.com/3127317/58926399-af1bb080-877d-11e9-812e-7bdfdc78d271.png)

**Comment by devpato** [comment]
Well in your acse yes, but if you see your comment in that line it says //returns ["a"]; original array: **[1, 2, 3, "a", "b", "c", 5]** and your original array is set as **[1, 2, 3, 4, 5];**, so I think based on your comment you should change the original array to **[1, 2, 3, "a", "b", "c", 5]** that way you get **[a]**
![Capture](https://user-images.githubusercontent.com/11162114/58929822-ad1a0900-870d-11e9-96ba-4fcada4695a0.JPG)
