### ISSUE TITLE
Is JavaScript faster than server side script

### ISSUE THREAD

**Issue by inderpreetkaur0** [sudheerj/javascript-interview-questions#43]
Is JavaScript faster than server side script -
Yes, JavaScript is faster than server side script. Because JavaScript is a client-side script it does require any web server’s help for its computation or calculation. So JavaScript is always faster than any server-side script like ASP, PHP, etc.

Yes, JavaScript is faster than server side script. Because JavaScript is a client-side script it _**does not**_ require any web server’s help for its computation or calculation. So JavaScript is always faster than any server-side script like ASP, PHP, etc.

**Comment by sudheerj** [comment]
Can you please create it as a PR?
