### ISSUE TITLE
11. What is the output of below code in non-strict mode

### ISSUE THREAD

**Issue by inderpreetkaur0** [sudheerj/javascript-interview-questions#47]
const printNumbers = (first, second, first) => {
  console.log(first, second, first);
}
printNumbers(1, 2, 3);

const printNumbersArrow = (first, second, first) => {
  console.log(first, second, first);
}
printNumbersArrow(1, 2, 3);

Wrong answer as arrow functions throw error with duplicate params. I think you want to put normal functions here.

**Comment by sudheerj** [comment]
Thanks for the finding. Q11 is for normal function and Q12 is for arrow functions.

**Comment by vikashssingh** [comment]
output 3,2,3
