### ISSUE TITLE
Q.223 What are primitive data types 

### ISSUE THREAD

**Issue by i-kay** [sudheerj/javascript-interview-questions#49]
I think primitive data types are these below, not "null" but "object". Also, It is a duplicate of Q.78.

1. string
2. number
3. boolean
4. null(x) -> object(o) 
5. undefined

**Comment by sudheerj** [comment]
It is seamingly primitive as mentioned here https://developer.mozilla.org/en-US/docs/Glossary/null. There is some more clarification needed for this. By the way, I will remove the duplicate question. Thank you.

**Comment by devashishg** [comment]
Q78. 
There are 8 Data types, JS has 

- String
- Number
- Object
- Function
- Boolean
- Undefined
- BigInt (typeof 1000n)
- Symbol (typeof Symbol('a'))

**Comment by mfurkan60** [comment]
There are 6 primitive data types in Js  there are string, number, bigint, boolean, undefined and  null.
All primitives are immutable, i.e., they cannot be altered. It is important not to confuse a primitive itself with a variable assigned a primitive value. The variable may be reassigned a new value, but the existing value can not be changed in the ways that objects, arrays, and functions can be altered.
if you want to more detail => https://developer.mozilla.org/en-US/docs/Glossary/Primitive

**Comment by sudheerj** [comment]
I updated the primitive data types question with 7 types. By the way, I will replace Q.78 with another one to avoid duplicate.
