### ISSUE TITLE
What is a higher order function?

### ISSUE THREAD

**Issue by devpato** [sudheerj/javascript-interview-questions#5]
**Question 13.**
What is a higher order function?
**Current code:**
```
const increment = x => x+1;
const higherOrder = higherOrder(increment);
console.log(higherOrder(1));
```
**Returns Error:**

> VM890:2 Uncaught ReferenceError: Cannot access 'higherOrder' before initialization
>     at <anonymous>:2:21

**Comment by sudheerj** [comment]
This has been fixed
