### ISSUE TITLE
Answers for questions 350, 389 and 390 are missing

### ISSUE THREAD

**Issue by jcastrov** [sudheerj/javascript-interview-questions#68]
- [Question 350: Does javascript uses mixins](https://github.com/sudheerj/javascript-interview-questions#does-javascript-uses-mixins)
- [Question 389: What are different event loops](https://github.com/sudheerj/javascript-interview-questions#what-are-different-event-loops)
- [Question 390: What is the purpose of queueMicrotask](https://github.com/sudheerj/javascript-interview-questions#what-is-the-purpose-of-queuemicrotask)

**Comment by pawan521** [comment]
Hey Can I work on Question number 389 ?

**Comment by sudheerj** [comment]
@pawan521 Yes, Please

**Comment by sudheerj** [comment]
@pragyamittal0 Sure, Thanks.

**Comment by zba** [comment]
for mixin (350) answer is wrong you can do mixin using the following 
```
const CLASS_MIXIN = (BASE) => class extends BASE { // mixin declaration
}
class CLASS_PARENT {  // can also extend something "extends"

}
export class CLASS_CHILD extends CLASS_MIXIN(CLASS_PARENT) {
}
```

I think it is good to know :)

**Comment by sudheerj** [comment]
@zba Can you create a PR?

**Comment by zba** [comment]
> @zba Can you create a PR?

No, i not really good in writing natural language

**Comment by riyaz2014** [comment]
Hello I want to contribute for question 389 and 390. Kindly assign me that task please

**Comment by chinmayk26** [comment]
Hello, I will like to contribute for Question 389 and 390 . Can You assign it ?

**Comment by rashmipachpande** [comment]
Is there any contribution needed? I'm open to the contribution.

**Comment by JustGetAClass** [comment]
i am also open to contributing

**Comment by sudheerj** [comment]
The answers have been added. Please create PRs and your contribution is welcome :)
