### ISSUE TITLE
Q1. What are the possible ways to create javascript object?

### ISSUE THREAD

**Issue by a-aiman** [sudheerj/javascript-interview-questions#78]
IV. Constructor function
Create any function and apply the new operator to create object instances,

```
function Person(name){
   var object = {};
   object.name=name;
   object.age=21;
   return object;
}
var object = new Person("Sudheer");
```
since the description says it wants to create a new object instances, it should be:
```
function Person(name){
   this.name=name;
   this.age=21;
}
var object = new Person("Sudheer");
```
since the new operator already implicitly creates an empty object and returns it at the end. However, If the question simply wants a literal object, the new keyword can be dropped altogether.
```
function Person(name){
   var object = {};
   object.name=name;
   object.age=21;
   return object;
}
var object = Person("Sudheer");
```

**Comment by sudheerj** [comment]
Thanks @a-aiman for the finding. Corrected.
